# General configuration
baseURL = "https://diegodelemos.me/"
theme = "LoveIt"
title = "diegodelemos"

# Language
languageCode = "en"
languageName = "English"

# Author config
[author]
  name = "diegodelemos"
  email = "diegodelemos@pm.me"
  link = "https://diegodelemos.me/"

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

# Theme configuration
[params]
  title = "diegodelemos"
  gitRepo = "https://github.com/diegodelemos/diegodelemos.github.io.git"

  [params.header]
    [params.header.title]
      name = "diegodelemos"

  [params.footer]
    enable = true
    custom = ""
    # whether to show Hugo and theme info
    hugo = false
    # whether to show copyright info
    copyright = true
    # whether to show the author
    author = true
    # site creation time
    since = 2022

  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "diegodelemos"

  [params.search]
    enable = true
    # type of search engine ["lunr", "algolia"]
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = "Search"
    # max number of results length
    maxResultLength = 10
    # snippet length of the result
    snippetLength = 30
    # HTML tag name of the highlight part in results
    highlightTag = "em"
    # whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false

  [params.home]
    # amount of RSS pages
    # RSS 文章数目
    rss = 10
    [params.home.profile]
      enable = true
      gravatarEmail = "diegorgzrgz@gmail.com"
      avatarURL = ""
      subtitle = "Software Engineer"
      typeit = false
      # whether to show social links
      # 是否显示社交账号
      social = true
      disclaimer = "Tortilla architect."
    [params.home.posts]
      enable = false
  [params.social]
    GitHub = "diegodelemos"
    Linkedin = "diegodelemos/"
    Twitter = "diego_delemos"
    Gitlab = "diegodelemos"
    Keybase = "diegodelemos"
